description: LLaVA-1.5 image-text toxicity middle-layer extraction
name: llava-toxic-activations

parameters:
  batch_size: 2
  dataset: ["llava1"]
  device: cuda
  dtype: bfloat16
  model_path: llava-hf/llava-1.5-7b-hf
  num_workers: 4
  pooling_op: ["mean"]
  resume: 0
  seed: 42
  seq_len: 512
  tag: "llava-toxic-responses"
  module_names: [
    "model.language_model.layers.*.mlp.up_proj",
    "model.language_model.layers.*.mlp.gate_proj",
    "model.language_model.layers.*.mlp.down_proj"
  ]

command: "${PYTHON} -m scripts.compute_responses"
